site_name: Ch-aOS Documentation
site_url: https://Ch-aOS-Ch.github.io/Ch-aOS/
repo_url: https://github.com/Ch-aOS-Ch/Ch-aOS
repo_name: Ch-aOS-Ch/Ch-aOS

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

  features:
    - content.code.copy
    - content.code.select
    - navigation.instant
    - navigation.top

plugins:
  - search
  - mkdocstrings:
      handlers:
         python:
           paths: ['cli/src/chaos']

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
  - 'Introduction': 'index.md'
  - 'Getting Started': 'getting-started.md'
  - 'Core Concepts': 'core-concepts.md'
  - 'The Chopping Board': 'chopping-board.md'
  - 'Commands':
    - 'Apply': 'Commands/apply.md'
    - 'Management': 'Commands/management.md'
    - 'Styx': 'Commands/styx.md'
    - 'Explain': 'Commands/explain.md'
    - 'Team': 'Commands/team.md'
    - 'Secrets': 'Commands/secrets.md'
    - 'Ramble': 'Commands/ramble.md'
  - 'Advanced':
    - 'Fleet Management': 'Advanced/fleet.md'
    - 'Boats for your Fleet': 'Advanced/boats.md'
    - 'Pyinfra Connectors': 'Advanced/connectors.md'
    - 'Secret Providers': 'Advanced/providers.md'
    - 'Logbook': 'Advanced/logbook.md'
    - 'Composability': 'Advanced/composability.md'
  - 'Plugins':
    - 'Provider Plugins': 'Plugins/provider-plugins.md'
    - 'Registry': 'Plugins/styx.md'
    - 'Development': 'Plugins/development.md'
    - 'Connector development': 'Plugins/connectors.md'
    - 'Roles': 'Plugins/roles.md'
    - 'Limani': 'Plugins/limani.md'
