[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "charonte"
version = "0.1.0"
description = "Declarative OS installer and configuration manager for Arch Linux."
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "pyinfra",
    "omegaconf",
]

[project.scripts]
B-coin = "Ch-aronte.cli:main"

[tool.setuptools.packages.find]
where = ["src"]
