[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "charonte"
version = "0.1.0"
description = "Declarative OS installer and configuration manager for Arch Linux."
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "pyinfra",
    "omegaconf",
    "passlib>=1.7.4",
]

[project.scripts]
B-coin = "charonte.cli:main"

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
pythonpath = ["src"]

[project.entry-points."charonte.roles"]
packages     = "charonte.roles.pkgs.tasks.pkgs:main"
users        = "charonte.roles.users.tasks.users:run_user_logic"
repositories = "charonte.roles.repos.tasks.repos:run_repo_logic"
bootloader   = "charonte.roles.bootloader.tasks.bootloader:run_bootloader"
helpers      = "charonte.roles.aurHelper.tasks.helper:run_aur"
services     = "charonte.roles.services.tasks.services:run_service_logic"
region       = "charonte.roles.region.tasks.region:run_region_logic"
reflector    = "charonte.roles.reflector.tasks.reflector:reflectorLogic"

