[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "chaos"
version = "0.1.0"
description = "Declarative OS configuration manager"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "pyinfra",
    "omegaconf",
    "passlib>=1.7.4",
    "argcomplete",
    "rich>=13.7.1",
    "hvac>=2.4.0",
    "requests>=2.32.4",
    "gitpython>=3.1.45",
    "gevent>=1.5",
    "MarkupSafe>=2.0",
    "cffi>=2.0.0",
    "PyYAML>=5.1.0",
    "charset_normalizer<4,>=2",
]

[project.scripts]
chaos = "chaos.cli:main"

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
pythonpath = ["src"]

[project.entry-points."chaos.explain"]
chaos = "chaos.lib.explanations.chaos.chaos:ChaosExplain"
secrets = "chaos.lib.explanations.secrets.secrets:SecretsExplain"
ramble = "chaos.lib.explanations.ramble.ramble:RambleExplain"
team = "chaos.lib.explanations.team.team:TeamExplain"
apply = "chaos.lib.explanations.apply.apply:ApplyExplain"
yourself = "chaos.lib.explanations.myself.myself:ExplainMyself"

